// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuMVghUcokPMJK7Z9t3OKLKfsijIQGUNI',
    appId: '1:799448347689:web:7a62e8a8951e8a3cf01838',
    messagingSenderId: '799448347689',
    projectId: 'cardoc-391614',
    authDomain: 'cardoc-391614.firebaseapp.com',
    storageBucket: 'cardoc-391614.appspot.com',
    measurementId: 'G-JV7WN33ZYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTQQH4iziWoHJL_zyefWvJrhCEofYaifM',
    appId: '1:799448347689:android:a1df3a80e4133512f01838',
    messagingSenderId: '799448347689',
    projectId: 'cardoc-391614',
    storageBucket: 'cardoc-391614.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeHAj0dj_QjniDMzQKyGEBElUyBUoxTog',
    appId: '1:799448347689:ios:f73d14ecc29ce5bdf01838',
    messagingSenderId: '799448347689',
    projectId: 'cardoc-391614',
    storageBucket: 'cardoc-391614.appspot.com',
    androidClientId: '799448347689-8ccichu6r0mr1igqg1vlioma4pjlbsuk.apps.googleusercontent.com',
    iosClientId: '799448347689-cupm1g712bjao1bq33a1npmt9252eg2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeHAj0dj_QjniDMzQKyGEBElUyBUoxTog',
    appId: '1:799448347689:ios:383634737247f65af01838',
    messagingSenderId: '799448347689',
    projectId: 'cardoc-391614',
    storageBucket: 'cardoc-391614.appspot.com',
    androidClientId: '799448347689-8ccichu6r0mr1igqg1vlioma4pjlbsuk.apps.googleusercontent.com',
    iosClientId: '799448347689-t5csfup7it71en13n1ao77s0g80eou51.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardoc.RunnerTests',
  );
}
